import assert from 'node:assert/strict';
globalThis.location={search:''};
const state=await import('../src/core/state.js?v=1.6.2');
const {POS_AB,POSN}=await import('../src/data/abilities.js?v=1.6.2');
assert.deepEqual(POS_AB.TW,['sta','vel','ctl','brk','con','pow','spd','eye']);
assert.equal(POSN.TW,'二刀流');
state.setS(state.newState('二刀流測試',17,'TW',null));
assert.equal(state.S.pos,'TW');
assert.equal(state.S.twOrigin,'tap');
assert.equal(state.S.dpos,'DH');
assert.equal(typeof state.S.ab.vel,'number');
assert.equal(typeof state.S.ab.con,'number');
assert.equal(typeof state.S.pot.vel,'number');
assert.equal(typeof state.S.pot.con,'number');
assert.ok(Math.max(state.S.pot.vel,state.S.pot.ctl,state.S.pot.brk)>=70);
assert.ok(Math.max(state.S.pot.con,state.S.pot.pow,state.S.pot.spd,state.S.pot.eye)>=72);
console.log('Two-way structure smoke test: PASS');
