import assert from 'node:assert/strict';
globalThis.location={search:''};
const state=await import('../src/core/state.js');
const {POS_AB,POSN}=await import('../src/data/abilities.js');
const tw=await import('../src/engine/twoway.js');
assert.deepEqual(POS_AB.TW,['sta','vel','ctl','brk','con','pow','spd','eye']);
assert.equal(POSN.TW,'二刀流');
state.setS(state.newState('二刀流測試',17,'TW',null));
assert.equal(state.S.pos,'TW');
assert.equal(state.S.twOrigin,'tap');
assert.equal(state.S.dpos,'DH');
assert.equal(typeof state.S.ab.vel,'number');
assert.equal(typeof state.S.ab.con,'number');
assert.equal(typeof state.S.pot.vel,'number');
assert.equal(typeof state.S.pot.con,'number');
assert.ok(tw.isTwoWay());
assert.ok(tw.twPitchOVR()>0);
assert.ok(tw.twBatOVR()>0);
assert.ok(tw.twOVR()>0);
assert.deepEqual(tw.splitTwoWayStat({G:120,PA:480,AB:430,H:120,HR:20,BB:45,GP:28,IP:170,pH:150,pBB:55,pHR:12,SO:160,ER:55,W:14,L:6,SV:0}),{batting:{G:120,PA:480,AB:430,H:120,HR:20,BB:45},pitching:{GP:28,IP:170,pH:150,pHR:12,pBB:55,SO:160,ER:55,W:14,L:6,SV:0}});
console.log('Two-way structure smoke test: PASS');
