import {SEED, setSeed, seedInit} from './core/rng.js?v=1.5.30';
import {S, setS, newState} from './core/state.js?v=1.5.30';
import {APP_VER} from './config.js?v=1.5.30';
import {POSN} from './data/abilities.js?v=1.5.30';
import {teamDisplayName} from './data/teams.js?v=1.5.30';
import {$, card, modalClose, actToggleSync} from './ui/dom.js?v=1.5.30';
import {THEME_KEY, BIG_KEY, applyTheme, applyMobileUI, applyBigText, updDispSum} from './ui/prefs.js?v=1.5.30';
import {allocFullClose} from './ui/alloc.js?v=1.5.30';
import {TL, resetTL, renderTimeline, tlScrollTo} from './ui/timeline.js?v=1.5.30';
import {startYear} from './flow/phases.js?v=1.5.30';
['gesturestart','gesturechange'].forEach(t=>document.addEventListener(t,e=>e.preventDefault()));
(function(){let last=0,sx=0,sy=0,drag=false;document.addEventListener('touchstart',e=>{const t=e.touches[0];if(e.touches.length===1&&t){sx=t.clientX;sy=t.clientY;drag=false;}else drag=true;},{passive:true});document.addEventListener('touchmove',e=>{const t=e.touches[0];if(t&&(Math.abs(t.clientX-sx)>12||Math.abs(t.clientY-sy)>12))drag=true;},{passive:true});document.addEventListener('touchend',e=>{const now=Date.now(),fast=now-last<350;last=now;if(!fast||drag||e.changedTouches.length!==1||!e.cancelable)return;const t=e.changedTouches[0],el=document.elementFromPoint(t.clientX,t.clientY);if(el&&/^(INPUT|TEXTAREA|SELECT|LABEL)$/.test(el.tagName))return;e.preventDefault();if(el)el.click();},{passive:false});})();
(function(){const t=document.getElementById('act-toggle');if(t)t.onclick=()=>{document.getElementById('act').classList.toggle('collapsed');actToggleSync();};})();
(function(){try{applyMobileUI(localStorage.getItem('yakyu-mobile-ui')==='1');}catch(e){}document.querySelectorAll('#seg-ui button').forEach(b=>b.onclick=()=>applyMobileUI(b.dataset.u==='1'));try{applyBigText(localStorage.getItem(BIG_KEY)==='1');}catch(e){}document.querySelectorAll('#seg-big button').forEach(b=>b.onclick=()=>applyBigText(b.dataset.b==='1'));const afc=$('af-close');if(afc)afc.onclick=allocFullClose;window.addEventListener('resize',updDispSum);(function(){const det=document.getElementById('fld-display');if(!det)return;const body=document.getElementById('disp-body'),sum=det.querySelector('summary');if(!body||!sum)return;let anim=null;const sync=on=>{body.hidden=!on;sum.setAttribute('aria-expanded',on?'true':'false');};const focusPref=()=>{(body.querySelector('#seg-theme button.on')||body.querySelector('button'))?.focus();};sync(det.open);det.addEventListener('toggle',()=>{if(!anim)sync(det.open);});sum.addEventListener('click',ev=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;ev.preventDefault();if(anim){anim.cancel();anim=null;}const opening=!det.open;if(opening){det.open=true;sync(true);}const h=body.getBoundingClientRect().height;body.style.overflow='hidden';anim=body.animate({height:opening?['0px',h+'px']:[h+'px','0px'],opacity:opening?[0,1]:[1,0]},{duration:280,easing:'ease'});anim.onfinish=()=>{body.style.overflow='';anim=null;if(!opening){det.open=false;sync(false);}};});sum.addEventListener('keydown',ev=>{if(ev.key!=='Enter'&&ev.key!==' ')return;const opening=!det.open;ev.preventDefault();sum.click();if(opening)setTimeout(focusPref,matchMedia('(prefers-reduced-motion: reduce)').matches?0:300);});})();let t='a';try{t=localStorage.getItem(THEME_KEY)||'a';}catch(e){}document.querySelectorAll('#seg-theme button').forEach(b=>b.onclick=()=>applyTheme(b.dataset.t));applyTheme(t);['tl-list','tl-strip'].forEach(id=>{const el=$(id);if(el)el.onclick=ev=>{const n=ev.target.closest('[data-i]');if(n)tlScrollTo(TL[+n.dataset.i]);};if(el)el.onkeydown=ev=>{if(ev.key!=='Enter'&&ev.key!==' ')return;const n=ev.target.closest('[data-i]');if(!n)return;ev.preventDefault();tlScrollTo(TL[+n.dataset.i]);};});const md=$('modal');if(md)md.onclick=ev=>{if(ev.target===md)modalClose();};document.addEventListener('keydown',ev=>{if(ev.key==='Escape'){modalClose();allocFullClose();}});})();
let selPos='P';
const DEFAULT_PLAYERS={P:{name:'有有子',jersey:11},IF:{name:'抹茶多',jersey:13},TW:{name:'二刀流君',jersey:17}};
const DEFAULT_PLAYER_PAIRS=[DEFAULT_PLAYERS.P,DEFAULT_PLAYERS.IF,DEFAULT_PLAYERS.TW,{name:'藥帝士',jersey:23},{name:'黃鎖頭',jersey:22}];
function defaultPlayer(pos){if(DEFAULT_PLAYERS[pos])return DEFAULT_PLAYERS[pos];return DEFAULT_PLAYER_PAIRS[3+Math.floor(Math.random()*2)];}
const PLAYER_NAME_KEY='yakyu-player-name',PLAYER_JERSEY_KEY='yakyu-player-jersey';
try{$('in-name').value=(localStorage.getItem(PLAYER_NAME_KEY)||'').slice(0,10);$('in-number').value=(localStorage.getItem(PLAYER_JERSEY_KEY)||'').slice(0,2);}catch(e){}
$('seed-show').value=SEED;$('seed-re').onclick=e=>{e.preventDefault();setSeed(Math.random().toString(36).slice(2,10));$('seed-show').value=SEED;};
document.querySelectorAll('#seg-pos button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#seg-pos button').forEach(x=>x.classList.remove('on'));b.classList.add('on');selPos=b.dataset.v;});
try{const posQ=new URLSearchParams(location.search).get('pos');if(posQ&&['P','C','IF','OF','TW'].includes(posQ)){selPos=posQ;document.querySelectorAll('#seg-pos button').forEach(x=>x.classList.toggle('on',x.dataset.v===posQ));}}catch(e){}
let careerStarted=false;
$('btn-start').onclick=()=>{if(careerStarted||S)return;const sv=$('seed-show').value.trim();if(sv)setSeed(sv);history.replaceState(null,'','?seed='+encodeURIComponent(SEED)+'&pos='+encodeURIComponent(selPos));seedInit(SEED);const enteredName=$('in-name').value.trim();const rawNo=$('in-number').value.trim();const useDefault=!enteredName&&!rawNo;let nm=enteredName,jersey=Number(rawNo);if(useDefault){const def=defaultPlayer(selPos);nm=def.name;jersey=def.jersey;}else{if(!nm){$('in-name').setCustomValidity('請輸入球員姓名，或將姓名與背號都留空使用預設球員。');$('in-name').reportValidity();return;}$('in-name').setCustomValidity('');if(rawNo===''||!Number.isInteger(jersey)||jersey<0||jersey>99){$('in-number').setCustomValidity('背號請輸入 0～99 的整數，或將姓名與背號都留空使用預設球員。');$('in-number').reportValidity();return;}}$('in-name').setCustomValidity('');$('in-number').setCustomValidity('');if(!useDefault){try{localStorage.setItem(PLAYER_NAME_KEY,nm);localStorage.setItem(PLAYER_JERSEY_KEY,String(jersey));}catch(e){}}careerStarted=true;const startBtn=$('btn-start');if(startBtn)startBtn.disabled=true;setS(newState(nm,jersey,selPos,null));S.teamName=function(){return teamDisplayName(this);};$('start').style.display='none';$('board').style.display='';$('act').style.display='';resetTL();renderTimeline();const ts=$('tl-seed');if(ts)ts.textContent=SEED;card('info','球員誕生',`${S.year} 年春天，${POSN[S.pos]} <b class="hl">${S.name}</b> 加入 <b class="hl">${S.team}</b> 棒球隊。雄心壯志，野心勃勃，他的世界正要因為棒球展開。<br><span style="color:var(--dim);font-size:12px">提示：22 歲前累積擲出 5 次「6」可覺醒隱藏素質。重整頁面不會保存進度，同一種子可重播。</span>`);startYear();};
(function(){if(!/^https?:$/.test(location.protocol))return;try{const dir=location.origin+location.pathname.replace(/[^/]*$/,'');const mf={id:dir,name:document.title||'YaKyoLife - 棒球人生模擬器',short_name:'YaKyoLife',description:'從日本高校到名人堂，一場種子化的日本棒球員生涯模擬。',lang:'zh-Hant',start_url:dir,scope:dir,display:'standalone',background_color:'#081510',theme_color:'#081510',icons:[{src:dir+'assets/app-icon-192.png',sizes:'192x192',type:'image/png',purpose:'any'},{src:dir+'assets/app-icon-512.png',sizes:'512x512',type:'image/png',purpose:'any'},{src:dir+'assets/app-icon-512.png',sizes:'512x512',type:'image/png',purpose:'maskable'}]};const l=document.createElement('link');l.rel='manifest';l.href=URL.createObjectURL(new Blob([JSON.stringify(mf)],{type:'application/manifest+json'}));document.head.appendChild(l);}catch(e){}})();
(function(){const vb=document.getElementById('ver-badge');if(vb)vb.textContent=APP_VER;const tv=document.getElementById('tl-ver');if(tv)tv.textContent=APP_VER;const gv=document.getElementById('game-ver');if(gv)gv.textContent=APP_VER;})();
(function(){const cell=document.getElementById('bd-sal-cell');if(!cell)return;cell.addEventListener('click',()=>cell.classList.toggle('show'));if(window.matchMedia('(hover:hover)').matches)cell.addEventListener('mouseleave',()=>cell.classList.remove('show'));})();
